name: bilibili_live
channels:
  - defaults
dependencies:
  - python=3.11.9
  - pip
  - pip:
    - altgraph
    - certifi
    - charset-normalizer
    - idna
    - packaging
    - pefile
    - pyinstaller
    - pyinstaller-hooks-contrib
    - pywin32-ctypes
    - requests
    - urllib3